### ISSUE TITLE
API remarks from bold-geo

### ISSUE THREAD

**Issue by jkittner** [RUBclim/d2r-api#7]
- [x] document the labeling (right vs. left) of hourly aggregates and daily aggregates #8 
- ~Allow the data-endpoint to return data from multiple stations either allow 3 - 15 via an array of station id~
    - ~test the performance - likely the maximum time interval has to be reduced or dynamically scaled~
    -  ~It might be even faster to make requests in parallel from the front end~
    **The above is not possible, since not every station has the same parameters. Merging stations with different types (i.e. biomet with temp rh) is very complicated, especially when it comes to providing helpful error messages**
- [x] Implement and API for the histogram ~providing the bins directly~ #12 
- [x] Districts are killed completely. I am not so keen on removing them already since as some other stuff they might come back. We may hide them behind a feature flag or just leave them #9 
- [x] Fix CORS - allow localhost #10
